allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@scarf/scarf': true
  '@sentry/cli': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js: true
  core-js-pure: true
  protobufjs: true
  sharp: true
  tesseract.js: false
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true

